import img from '../../../../assets/phone.png';

export const productsFromServer = [
  {
    id: 'dsc2531abfs',
    price: { current: 189.99, old: 219.99 },
    name: 'Apple iPhone 13 Pro - 256GB - Graphite (Unlocked)',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: 9.99,
    orders: 87,
    rating: 4.8,
    sellerId: 'Apple Store',
  },
  {
    id: 'xzc1569bcsd',
    price: { current: 499.99 },
    name: 'bSamsung Galaxy S21 Ultra 5G - 256GB - Phantom Black (Unlocked)',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: 12.99,
    orders: 62,
    rating: 4.6,
    sellerId: 'Samsung Official Store',
  },
  {
    id: 'fgd2456kliu',
    price: { current: 79.99, old: 99.99 },
    name: 'Sony WH-1000XM4 Wireless Noise-Cancelling Headphones - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: 5.99,
    orders: 104,
    rating: 4.9,
    sellerId: 'Sony Electronics',
  },
  {
    id: 'plm9874jklp',
    price: { current: 149.99 },
    name: 'dFitbit Charge 5 Fitness Tracker - Lunar White/Soft Gold',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: 7.99,
    orders: 36,
    rating: 4.2,
    sellerId: 'Fitbit Official Store',
  },
  {
    id: 'jkl3546oiuy',
    price: { current: 219.99 },
    name: 'eDyson V11 Absolute Pro Cordless Vacuum Cleaner - Blue/Nickel',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: 19.99,
    orders: 22,
    rating: 4.7,
    sellerId: 'Dyson Official Store',
  },
  {
    id: 'hgf5468ewqs',
    price: { current: 1199.99 },
    name: 'LG OLED65CXPUA 65" OLED 4K UHD Smart TV',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: 49.99,
    orders: 14,
    rating: 4.5,
    sellerId: 'LG Electronics',
  },
  {
    id: 'qwe0976uytr',
    price: { current: 29.99, old: 39.99 },
    name: 'Logitech M705 Marathon Wireless Mouse - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: 4.99,
    orders: 98,
    rating: 4.3,
    sellerId: 'Logitech Official Store',
  },
  {
    id: 'sxeyg531daczs516',
    price: { current: 41 },
    name: 'fGoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 0.7,
    sellerId: 'catalog name',
  },
  {
    id: 'g1daczs517',
    price: { current: 41 },
    name: 'cGoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 4,
    sellerId: 'catalog name',
  },
  {
    id: 'azxdaczs518',
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 4,
    sellerId: 'catalog name',
  },
  {
    id: '1sdaczs519',
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 4,
    sellerId: 'catalog name',
  },
];
