import { productTypes } from 'entities/Product';

import img from '../assets/phone.png';

export const productsFromServer: productTypes.ProductRowType[] = [
  {
    id: '1dasda622v3',
    price: { current: 41, old: 599 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 2.3,
  },
  {
    id: 'da1dasda622v3',
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 4.1,
  },
  {
    id: '1dafsda622v3',
    price: { current: 41, old: 1999 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 2.5,
  },
  {
    id: '1daxdassda622v3',
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 5,
  },
  {
    id: '161dasda622v3',
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 1.2,
  },
  {
    id: 'dasdas1dasda622v3',
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 0.7,
  },
  {
    id: '1dfasda622v3',
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 4,
  },
  {
    id: 'xcz1dasda622v3',
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 4,
  },
  {
    id: '1mvbndasda622v3',
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 4,
  },
];
