import { ProductRowType } from 'entities/Product';

import img from '../assets/phone.png';

export const productsFromServer: ProductRowType[] = [
  {
    id: 11,
    price: { current: 41, old: 599 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 2.3,
  },
  {
    id: 12,
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 4.1,
  },
  {
    id: 13,
    price: { current: 41, old: 1999 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 2.5,
  },
  {
    id: 14,
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 5,
  },
  {
    id: 15,
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 1.2,
  },
  {
    id: 16,
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 0.7,
  },
  {
    id: 17,
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 4,
  },
  {
    id: 18,
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 4,
  },
  {
    id: 19,
    price: { current: 41 },
    name: 'GoPro HERO6 4K Action Camera - Black',
    mainPhoto: { url: img, thumbUrl: img },
    deliveryCost: '0',
    orders: 14,
    rating: 4,
  },
];
